name: Automatic PR
on:
  push:
    branches: ['track-list']

jobs:
  pull-request:
    name: Open PR to branch-2022
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "branch-2023"
        pr_title: "Pulling ${{ github.ref }} into branch-2023"
        pr_body: "Automatic PR"
        github_token: ${{ secrets.GITHUB_TOKEN }}
